### ISSUE TITLE
你好打扰了，本人小白，本地运行你的代码，报错

### ISSUE THREAD

**Issue by Ericliu68** [howie6879/Sanic-For-Pythoneer#4]
https://github.com/howie6879/Sanic-For-Pythoneer/blob/master/examples/demo01/news.py

Traceback (most recent call last):
  File "/home/liu/PycharmProjects/sanic_test/run.py", line 45, in <module>
    async def index(request, page=1):
  File "/home/liu/anaconda3/envs/flask_blog/lib/python3.6/site-packages/sanic/app.py", line 197, in response
    args = list(signature(handler).parameters.keys())
  File "/home/liu/anaconda3/envs/flask_blog/lib/python3.6/inspect.py", line 3065, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/home/liu/anaconda3/envs/flask_blog/lib/python3.6/inspect.py", line 2815, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/home/liu/anaconda3/envs/flask_blog/lib/python3.6/inspect.py", line 2193, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: ([Route(handler=<function index at 0x7fecec5b6620>, methods=frozenset({'GET'}), pattern=re.compile('^/$'), parameters=[], name='index', uri='/')], <function index at 0x7fecec5b6620>) is not a callable object

**Comment by skylandYao** [comment]
同问，咋解决呢

**Comment by howie6879** [comment]
版本原因
